name: ici_check
description: "A new Flutter project."
publish_to: 'none'
version: 0.6.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  uuid: ^4.5.2
  excel: ^4.0.6
  spreadsheet_decoder: ^2.0.1 # La usaremos SOLO para Importar (Es blindada)
  file_picker: ^8.1.4  # Versión más reciente  path_provider: ^2.1.1
  share_plus: ^7.2.0  # Para "exportar" (compartir el archivo) en móvil fácilmente
  permission_handler: ^11.3.1  # AGREGAR ESTA
  image_picker: ^1.0.4
  intl: ^0.18.0
  signature: ^5.4.0  # Para las firmas
  pdf: ^3.10.0
  path_provider: ^2.1.1
  printing: ^5.11.0
  firebase_storage: ^13.0.6  # Agrega esta línea si no la tienes
  flutter_image_compress: ^2.1.0   # ✅ Comprimir automáticamente
  crypto: ^3.0.3                   # ✅ Nombres únicos
  gal: ^2.3.0  # <--- Esta es la nueva dependencia para guardar fotos en la galería local del dispositivo
  open_filex: ^4.5.0  # Usamos open_filex que es la versión mantenida

  cloud_functions: ^6.0.6 # O la versión compatible con tu firebase_core
  url_launcher: ^6.2.5
  http: ^1.2.0
  sticky_headers: ^0.3.0+2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
